/pcd2pgm:
  ros__parameters:
    file_directory: /home/grange/Program/Tinker/pointcloud2map_tinker/
    file_name: asd
    flag_pass_through: false
    map_resolution: 0.05
    map_topic_name: map
    thre_radius: 0.5
    thre_z_max: 15.0
    thre_z_min: 0.05
    thres_point_count: 5
    use_sim_time: false
